### ISSUE TITLE
Component looks not the way it should

### ISSUE THREAD

**Issue by mamaevads** [softsimon/ngx-bootrap-multiselect#194]
Why does the component look like that? 

![9rqhruxfjrc](https://user-images.githubusercontent.com/14263431/26976083-120bdb00-4d2b-11e7-8d99-40c01a33e8c6.jpg)

**Comment by chris--jones** [comment]
Hard to tell, can you link to an example?

Might be conflicting css rules.

**Comment by revok** [comment]
Seems like this is caused by incompatibilities between bootstrap 3 and 4. In particular, bootstrap 4 no longer uses btn-default. It has been replaced with btn-secondary (which looks pretty ugly in my opinion). 

I have worked around the issue in my angular 2 application by adding the following css rules (ignore the ::ng-deep selectors, they are specific to angular 2):

::ng-deep .btn-default {
    color: #333;
    background-color: #fff;
    border-color: #ccc;
}

::ng-deep .dropdown-item>a {
    color: #212529!important;
    text-decoration: none!important;
}

::ng-deep .dropdown-item:hover {
    background-color:rgb(228, 228, 228);
}
