### ISSUE TITLE
Feature Request: Display image with label

### ISSUE THREAD

**Issue by ankurshah32** [softsimon/ngx-bootrap-multiselect#204]
I want to add image to list item in dropdown. How can we achieve this? Also i want show the selected item with image in selected box.

**Comment by gund** [comment]
I guess this is a valid scenario to let users define how they want to render their items.

What can be done is to provide user the ability to define the template where he can define his own html required and that will be stamped out as an items in the dropdown.

As a reference of valid implementation you can have a look at [NgbTypeAhead](https://ng-bootstrap.github.io/#/components/typeahead/api) at the `resultTemplate` input property.

I also feel like it will be a good idea to let user provide template for every string like that because than i18n will be much easier (by using Angular's i18n directives or by using custom translate pipes).

What do you think?

**Comment by thebf** [comment]
![image](https://user-images.githubusercontent.com/18346679/33243919-af62b7b8-d2ee-11e7-8f18-3d78c2a2f58d.png)
Something like this?

Adding images to the top most box shouldn't be to hard. This modification is passed as a setting in my local modification that I am working on.
