### ISSUE TITLE
IE11: uncheckall function throw error "Object doesn't support property or method 'includes'"

### ISSUE THREAD

**Issue by chawgid** [softsimon/ngx-bootrap-multiselect#305]
IE11: uncheckall function throw error "Object doesn't support property or method 'includes'".

IE11 is not able to use .includes to filter array.

i am using this component in a solution where the main user will use IE11 as default browser, So if you guys could make the change to use .indexOf() instead of includes() to filter  the array that will be more than awesome. Thanks!

**Comment by travis1234** [comment]
Yep, can confirm this is an issue in IE11 and I also have a corporate client who is stuck using IE 11.
If you could bump this issues to the top of the list it would be much appreciated.
  
A quick search found a number of possible solutions in the below SO thread.
I'm not really sure where to start making the changes requires otherwise I would raise a pull request.

https://stackoverflow.com/questions/31119300/ie11-object-doesnt-support-property-or-method-includes-javascript-window

**Comment by sukhminderx** [comment]
hi

I too am facing the same issue.
It seems to occur at:
unCheckedOptions_1 = checkedOptions.filter(function (item) { return unCheckedOptions_1.includes(item); });

in unCheckAll function in  dropdown.component.js

Is there any update to this.
Thanks

**Comment by sukhminderx** [comment]
Hi

I solved it by adding this to the polyfills.ts:

 import 'core-js/es7/array';

It will add the es7 array methodsas a polyfill.

Thanks

**Comment by travis1234** [comment]
@sukhminderx Thanks for the workaround!

**Comment by GregKass** [comment]
Current solution can be found here (under "UPDATE 2017"):

https://stackoverflow.com/questions/35140718/angular-2-4-not-working-in-ie11

**Comment by frontend123** [comment]
@sukhminderx This worked for me. Thanks..!

**Comment by chris--jones** [comment]
Suggested fix is here: #344

**Comment by anandSep90** [comment]
Am also facing the same issue. Is the fix available in latest version 1.63 or else have to the work around

**Comment by psined1** [comment]
any idea when this is fixed? Why not just use Array.prototype.indexOf ?
