### ISSUE TITLE
[Feature request]Can we add the ability to choose which property to show in dropdown list?

### ISSUE THREAD

**Issue by liwonder** [softsimon/ngx-bootrap-multiselect#355]
It's now default to show "option.name" in dropdown list, I think it will be a good feature letting user choose which property to show in dropdown list.

**Comment by chris--jones** [comment]
You should map your data to a model appropriate for display in the dropdown list. The name can be anything you want.

**Comment by madhavmahesh1969** [comment]
Hi Chris,

Can you help me in understanding like how to map the data to a model appropriate for display in the dropdown list.

 [
    {  
        "name":       "sonoo",   
        "salary":      56000,   
        "married":    true  
    } ,
        {  
        "name":       "sonoo",   
        "salary":      56000,   
        "married":    true  
    }]
I have to show the multiselect drop down on the headers of a table so that the multiselect should show the values corresponding to the cloumn, 

How can I map the salary to the multiselect instead of name.
