### ISSUE TITLE
Question: Demo no longer working

### ISSUE THREAD

**Issue by Local9** [softsimon/ngx-bootrap-multiselect#380]
Do you have an Angular Branch 2 Version 4 and above example?

**Comment by GregKass** [comment]
So, one solution would be to use rawgit:

https://github.com/angular/angular.js/issues/16450#issuecomment-364855999

Another would be to use unpkg.com and access the npm version instead of git. This second method would likely be more persistent (although there is always the left-pad cautionary tale). I'd do it myself, but I don't have access to the setup files, afaik.

@softsimon @chris--jones

**Comment by psined1** [comment]
Any idea when this going to be fixed?

**Comment by nimatullah** [comment]
Any one?
